---
- name: Install Apache Tomcat  Server
  hosts: 192.168.121.143
  become: true
  tasks:
  - name: Install Java
    yum:
      name: java
      state: latest
  - name: Download Apache Tomcat Server Package
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.58/bin/apache-tomcat-9.0.58.tar.gz
      dest: /opt
  - name: Extracting the  Apache Tomcat Server Tar File.
    unarchive:
      src: /opt/apache-tomcat-9.0.58.tar.gz
      dest: /opt
      remote_src: yes
  - name: Download Apache Maven Software
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
      dest: /opt
  - name: Extracting the  Apache Maven Software
    unarchive:
      src: /opt/apache-maven-3.8.4-bin.tar.gz
      dest: /opt
      remote_src: yes
  - name: Downloading the The Jenkins.war file
    get_url: 
      url: https://get.jenkins.io/war-stable/2.319.3/jenkins.war
      dest: /opt/apache-tomcat-9.0.58/webapps
  - name: Starting the Apache Tomcat Server Software
    shell: nohup /opt/apache-tomcat-9.0.58/bin/startup.sh




192.168.19.133  controller.com  controller
192.168.19.145  jenkinsslave.com  jenkinsslave
192.168.19.155  jenkinsmaster.com jenkinsmaster




